### ISSUE TITLE
Dynamic/calibration data can be moved to req/rep channel

### ISSUE THREAD

**Issue by basvanberckel** [QuTech-Delft/compute-runtime-schema#6]
There are two channels between the job processor (2200) and control-software (2300), a request/reply channel and a pub/sub channel. Currently, the req/rep channel transfers messages related to execution, as well as get_static, which retrieves the static data about control software during startup of the job processor. The pub/sub channels transfers messages containing the latest status of the control software, as well as the dynamic/calibration data.

In this setup, after calibration of the hardware, the job processor needs the dynamic data to be received and processed before it can start processing new jobs. The recipients of the two separate channels on the job processor side are, necessarily, run in parallel. This means that there is a possible race condition between the dynamic data being received and processed and the job processor restarting execution of jobs. This would require syncing between the two paths in multiple locations and lead to unnecessary complexity.

Additionally, the only time where the job processor needs to receive the dynamic/calibration data is after the system was down for calibration (or for maintenance etc.). This state change is already announced through the status message, so the job processor knows when the dynamic data has (possibly) changed. Therefore, this data can be requested over the req/rep channel instead of awaited in the pub/sub channel (after a trigger_publish message, as is the current proposal). 

The proposal is to replace the trigger_publish message with a get_dynamic message, similar to the existing get_static message. This can then be sent, and its response received, over the req/rep channel when needed, i.e. after a status change from "calibrating"/"offline" to "idle" or after a restart of the job processor.

This would eliminate complexity on the job processor side related to parallel execution; would give assurance that updated dynamic data is received (and not published to a pub/sub channel without subscribers); and would get rid of the superfluous of periodic publishing of the dynamic data, as a change in this data will only ever follow a change in the already periodically published status.

**Comment by basvanberckel** [comment]
> Yes, that makes the systems more complicated. It would be great if we could avoid this (see also a [previous question](https://github.com/QuTech-Delft/compute-runtime-schema/pull/1#discussion_r1275884539) whether we need two communication channels).  

Conceptually, the status can change at any point regardless of the state of execution. In other words, a status update needs to be able to be delivered outside the request/reply message flow. Since a req/rep channel has to go back and forth between requests and reply, we can't use the existing req/rep channel for status updates. There are certainly ways of mixing these messages by using different communication methods, but in my opinion that would not make either system less complex, since you would still need to separate the different message flows within the application, instead of keeping the flows separated the whole time.

> Does the control software need to know the dynamic data before sending a job to the job processor? Our assumption was that this is just "interesting information" for the user and not critical to be synchronized.  

No, this is not critical in the sense that it hinders core functionality. However, since the calibration data from when a job was executed is linked to its results, a race condition might lead to the wrong (outdated) calibration data being linked. Which is probably not a breaking issue, but definitely seems sloppy.

> I like this proposal, because it makes the messages more uniform and makes the `trigger_publish` message obsolete. But the real benefit would come if we exchange all messages via req/rep (i.e. also the state messages). Then we could get rid of all parallel execution.

I don't think this is possible without extra complexity to "hide" the concurrency. Of course, I'm open to ideas if it makes our systems less complex, but at this point I don't see a better way.

**Comment by mjhaye** [comment]
The proposal is ok with me. 

To be honest, I am not convinced by any race condition arguments. Given that everything gets passed over the network there is always plenty of room for race conditions unless there is a clear handshake protocol defined. 

The only, for me, valid reason to justify a separate channel is to have an independent alive monitoring mechanism. But, this is only useful if both:
- The backends implement this independently of the execution.
- The alive interval is significantly shorter than the maximum execution time (of a single exec).

I suspect the latter not to be the case and thus parallel communication not useful. The point is that that the job processor cannot do anything with the backend while the req/rep channel is blocked. So what would be the use of the parallel status message in that case if you cannot act upon it? And once the channel is unblocked again you can use it to retrieve any information you need (that could also be done in between init/terminate blocks).

**Comment by oschusler** [comment]
>  * The backends implement this independently of the execution.

This first bullet point is not up to me, so I can't really argue about it. 

> * The alive interval is significantly shorter than the maximum execution time (of a single exec).

This however should be the case. I looked up the frequency for the status message within the original QI stack. These message were sent every second, given that they also signal a heartbeat. Execution within that same stack can take up to tens of seconds. This means that the status interval is indeed significantly shorter. 

Do keep in mind that the 2200 just doesn't know what 2300 is doing. It might be executing, but it might also have crashed. For fast responses (either to the user, or with regard to resource allocation), we cannot rely on waiting for the REQ/REP returning, and then asking for the status. Even if we would implement time-outs (which we should), we would have to wait the entire time-out before we can respond. With (asynchronous) heartbeats, combined with a grace period, the QI2 platform can respond a lot quicker to any "status" change.

**Comment by mjhaye** [comment]
Thanks for reminding me about the anticipated durations. I had forgotten again (as usual).

I understand your reasoning but given the complexity it introduces it seems to me premature at the moment. Given these are exceptional cases after which human intervention is required anyway, I do not think it unreasonable that the user has to wait a little bit longer for detection (on the same time scale he/she had to wait anyway for the experiment to complete). And indeed, this requires time-out on the REQ, but that needs to be done anyway (unless you want to do a hard kill of your thread).

We could add, in the future, fancy stuff like a progress bar for execution, but that requires revisiting the interface anyway.

But also here, let's stop the discussion. It is perfectly fine to me if you take the final decision.
